blank_issues_enabled: false
contact_links:
  - name: Questions and Help
    url: https://github.com/szymdzum/typescript-result-monad/discussions/categories/q-a
    about: Please ask questions here if you need help with the library.
  - name: Feature Discussion
    url: https://github.com/szymdzum/typescript-result-monad/discussions/categories/ideas
    about: Discuss ideas for new features or improvements before creating a feature request.