name: Pull Request

on:
  pull_request:
    branches: [main]

# Add permissions section
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test:
    name: Test and Report Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run tests with coverage
        run: pnpm test:coverage
      - name: Report Coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
      - name: Run Performance Tests
        run: pnpm test:perf || true
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Thank you for your contribution! 🎉

            CI passed successfully on commit ${{ github.sha }}. Build artifacts are available.
          comment_tag: execution
          mode: recreate